# Generated by Django 3.0.8 on 2020-11-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
