# Generated by Django 3.0.8 on 2020-11-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.ImageField(upload_to='images/', verbose_name='avator')),
            ],
        ),
    ]
