# Generated by Django 3.0.8 on 2020-11-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garbage', '0002_delete_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=1000)),
                ('classification', models.TextField(max_length=1000)),
            ],
        ),
    ]
